/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ResultAnalyzerGateway */

#ifndef _Included_ResultAnalyzerGateway
#define _Included_ResultAnalyzerGateway
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ResultAnalyzerGateway
 * Method:    runAnalyseData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ResultAnalyzerGateway_runAnalyseData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ResultAnalyzerGateway
 * Method:    checkContainsPermutation
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ResultAnalyzerGateway_checkContainsPermutation
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
